### ISSUE TITLE
Grad-CAM and web UI codes

### ISSUE THREAD

**Issue by Benny0323** [ahmedeqbal/TB-DenseNet#1]
Could you provide the codes about Grad-CAM and web UI. THX!

**Comment by ahmedeqbal** [comment]
You can try (https://github.com/samson6460/tf_keras_gradcamplusplus) for grad-CAM, for UI, you can try Django framework and HTML Bootstrap,

**Comment by Benny0323** [comment]
Thanks！



發自我的iPhone


------------------ Original ------------------
From: Ahmed iqbal ***@***.***&gt;
Date: Mon,Jan 22,2024 10:51 PM
To: ahmedeqbal/TB-DenseNet ***@***.***&gt;
Cc: Zhanghao Chen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ahmedeqbal/TB-DenseNet] Grad-CAM and web UI codes (Issue #1)





 
You can try (https://github.com/samson6460/tf_keras_gradcamplusplus) for grad-CAM, for UI, you can try Django framework and HTML Bootstrap,
